# Generated by Django 4.1.1 on 2022-10-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianmodel',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
